# Generated by Django 4.2.5 on 2023-09-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, null=True)),
                ('class1', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID',)),
                ('Hindi', models.IntegerField()),
                ('English', models.IntegerField()),
                ('Chemistry', models.IntegerField()),
                ('Maths', models.IntegerField()),
                ('physics', models.IntegerField()),
            ],
        ),
    ]
